# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Set
version:      1.00
version_from: Set.pm
installdirs:  site
requires:
    Cwd:                           0.01
    Digest::MD5:                   0.01
    File::Temp:                    0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
